#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source "$ROOT_DIR/scripts/cel_stage1_last_layer/ssh_config.sh"
source "$ROOT_DIR/scripts/cel_stage1_last_layer/formal_candidate_registry.sh"

FILES_TO_SYNC=(
  "dialogue_kt/main.py"
  "dialogue_kt/training.py"
  "dialogue_kt/cel_methods.py"
  "scripts/cel_stage1_last_layer/check_formal_candidate_registry_alignment.py"
  "scripts/cel_stage1_last_layer/check_formal_surface_consistency.py"
  "scripts/cel_stage1_last_layer/check_ssh_formal_config.sh"
  "scripts/cel_stage1_last_layer/current_formal_state.py"
  "scripts/cel_stage1_last_layer/print_current_formal_next_action.py"
  "scripts/cel_stage1_last_layer/print_current_formal_manual_launch_steps.sh"
  "scripts/cel_stage1_last_layer/launch_round3_candidate_on_server.sh"
  "scripts/cel_stage1_last_layer/preflight_strict_full_train.sh"
  "scripts/cel_stage1_last_layer/print_recommended_wsl_ssh_alias.sh"
  "scripts/cel_stage1_last_layer/run_current_formal_next_action_via_ssh_alias.sh"
  "scripts/cel_stage1_last_layer/run_task_conditioned_controller.sh"
  "scripts/cel_stage1_last_layer/run_task_conditioned_controller_via_ssh_alias.sh"
  "scripts/cel_stage1_last_layer/start_task_conditioned_controller_background.sh"
  "scripts/cel_stage1_last_layer/start_current_formal_candidate_via_ssh_alias.sh"
  "scripts/cel_stage1_last_layer/start_formal_candidate.sh"
  "scripts/cel_stage1_last_layer/start_formal_candidate_via_ssh_alias.sh"
  "scripts/cel_stage1_last_layer/monitor_formal_candidate.sh"
  "scripts/cel_stage1_last_layer/monitor_formal_candidate_via_ssh_alias.sh"
  "scripts/cel_stage1_last_layer/finalize_formal_candidate.sh"
  "scripts/cel_stage1_last_layer/finalize_current_formal_candidate.sh"
  "scripts/cel_stage1_last_layer/finalize_formal_candidate_via_ssh_alias.sh"
  "scripts/cel_stage1_last_layer/finalize_current_formal_candidate_via_ssh_alias.sh"
  "scripts/cel_stage1_last_layer/review_formal_candidate.sh"
  "scripts/cel_stage1_last_layer/review_current_formal_candidate.sh"
  "scripts/cel_stage1_last_layer/review_formal_candidate_via_ssh_alias.sh"
  "scripts/cel_stage1_last_layer/review_current_formal_candidate_via_ssh_alias.sh"
  "scripts/cel_stage1_last_layer/rebuild_task_conditioned_reports.sh"
  "scripts/cel_stage1_last_layer/refresh_task_conditioned_round3_once.sh"
  "scripts/cel_stage1_last_layer/sync_code_to_server_via_ssh_alias.sh"
  "scripts/cel_stage1_last_layer/sync_code_to_server.sh"
  "scripts/cel_stage1_last_layer/sync_results_from_server_via_ssh_alias.sh"
  "scripts/cel_stage1_last_layer/sync_results_from_server.sh"
  "scripts/cel_stage1_last_layer/watch_task_conditioned_tuning.sh"
  "scripts/cel_stage1_last_layer/check_probability_bce_safety.py"
  "scripts/cel_stage1_last_layer/check_sync_manifest_coverage.py"
  "scripts/cel_stage1_last_layer/formal_queue_guard.py"
  "scripts/cel_stage1_last_layer/formal_queue_state.py"
  "scripts/cel_stage1_last_layer/task_conditioned_failure_utils.py"
  "scripts/cel_stage1_last_layer/formal_candidate_registry.py"
  "scripts/cel_stage1_last_layer/formal_candidate_registry.sh"
  "scripts/cel_stage1_last_layer/launch_round3_candidate_in_remote_repo.sh"
  "scripts/cel_stage1_last_layer/generate_comparison_report.py"
  "scripts/cel_stage1_last_layer/generate_detailed_analysis.py"
  "scripts/cel_stage1_last_layer/generate_formal_candidate_briefs.py"
  "scripts/cel_stage1_last_layer/generate_formal_candidate_config_diffs.py"
  "scripts/cel_stage1_last_layer/generate_status_summary.py"
  "scripts/cel_stage1_last_layer/generate_formal_experiment_audit.py"
  "scripts/cel_stage1_last_layer/generate_formal_method_protocol.py"
  "scripts/cel_stage1_last_layer/generate_formal_experiment_summary.py"
  "scripts/cel_stage1_last_layer/generate_strict_full_train_report.py"
  "scripts/cel_stage1_last_layer/print_formal_candidate_context.py"
  "scripts/cel_stage1_last_layer/print_manual_formal_launch_steps.sh"
  "scripts/cel_stage1_last_layer/check_formal_candidate_rerun_readiness.py"
  "scripts/cel_stage1_last_layer/scaffold_formal_candidate.py"
  "scripts/cel_stage1_last_layer/show_current_formal_runtime_health.sh"
  "scripts/cel_stage1_last_layer/ssh_config.sh"
  "scripts/cel_stage1_last_layer/update_baseline_record.py"
  "scripts/cel_stage1_last_layer/update_stage1_last_layer_record.py"
  "scripts/cel_stage1_last_layer/update_task_conditioned_tuning_loop.py"
  "scripts/cel_stage1_last_layer/run_task_conditioned_v26_bootstrap.sh"
  "scripts/cel_stage1_last_layer/run_task_conditioned_v26_calibrator_warmup.sh"
  "scripts/cel_stage1_last_layer/run_task_conditioned_v26_joint.sh"
  "scripts/cel_stage1_last_layer/audit_task_conditioned_v26_selftrained.py"
)

for key in "${FORMAL_CANDIDATE_KEYS[@]}"; do
  FILES_TO_SYNC+=("${FORMAL_RUN_SCRIPT_REL[$key]}")
done

for rel_path in "${FILES_TO_SYNC[@]}"; do
  local_path="$ROOT_DIR/$rel_path"
  remote_dir="$(dirname "$REMOTE_ROOT/$rel_path")"
  ssh_run "$SSH_TARGET" "mkdir -p '$remote_dir'"
  rsync -az -e "$(rsync_ssh_command)" "$local_path" "$SSH_TARGET:$REMOTE_ROOT/$rel_path"
done

echo "Synced ${#FILES_TO_SYNC[@]} files to $SSH_TARGET:$REMOTE_ROOT"
