import importlib

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import LoraConfig, PeftModel, get_peft_model, prepare_model_for_kbit_training

from dialogue_kt.utils import get_checkpoint_path

# 4-bit quantization config (NF4 with double quantization for best quality)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
)

def get_base_model(base_model_name: str, tokenizer: AutoTokenizer, quantize: bool,
                   eager_attention: bool = False, use_gradient_checkpointing: bool = True):
    if quantize:
        try:
            importlib.import_module("bitsandbytes")
        except Exception as exc:
            print(f"WARNING: Quantization requested but bitsandbytes not available ({exc}). Running without quantization.")
            quantize = False
    # When quantizing, bitsandbytes handles device placement — cannot use explicit device_map
    device_map = None if quantize else {"": 0}
    attn_kwargs = {"attn_implementation": "eager"} if eager_attention else {}
    base_model = AutoModelForCausalLM.from_pretrained(
        base_model_name,
        pad_token_id=tokenizer.pad_token_id,
        trust_remote_code=True,
        quantization_config=bnb_config if quantize else None,
        # f32 seems helpful for train/test time consistency when quantizing, bf16 performs best for non-quantized
        dtype=torch.float32 if quantize else torch.bfloat16,
        device_map=device_map,
        **attn_kwargs
    )
    base_model.config.use_cache = False
    base_model.config.pretraining_tp = 1
    # Enable gradient checkpointing to save memory
    # use_reentrant=True preserves the legacy behavior (less memory than non-reentrant)
    if use_gradient_checkpointing:
        base_model.gradient_checkpointing_enable(gradient_checkpointing_kwargs={"use_reentrant": True})
    else:
        base_model.gradient_checkpointing_disable()
    return base_model

def get_model(base_model_name: str, test: bool,
              model_name: str = None, pt_model_name: str = None,
              r: int = None, lora_alpha: int = None,
              quantize: bool = True, use_gradient_checkpointing: bool = True,
              eager_attention: bool = False):
    tokenizer = AutoTokenizer.from_pretrained(base_model_name, padding_side="right", trust_remote_code=True)
    # Set pad_token: if bos_token exists use it, otherwise use eos_token
    if tokenizer.pad_token is None:
        if tokenizer.bos_token is not None:
            tokenizer.pad_token = tokenizer.bos_token
        else:
            tokenizer.pad_token = tokenizer.eos_token
    model = get_base_model(
        base_model_name,
        tokenizer,
        quantize,
        eager_attention=eager_attention,
        use_gradient_checkpointing=use_gradient_checkpointing,
    )
    if test and model_name:
        # Note we are loading adapter on quantized model and not merging
        # Recommended here - https://huggingface.co/docs/trl/main/en/dpo_trainer#downsides-to-merging-qlora-before-dpo-approach-2
        # Also prevents empty responses generated by Llama models
        print("Initializing inference-time model from fine-tuned LoRA adapters")
        model = PeftModel.from_pretrained(model, get_checkpoint_path(model_name))
    elif not test:
        if quantize:
            model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=use_gradient_checkpointing)
        if pt_model_name:
            print("Initializing trainable model from pre-trained LoRA adapters")
            model = PeftModel.from_pretrained(model, get_checkpoint_path(pt_model_name), is_trainable=True, adapter_name="default")
        else:
            print("Initializing trainable model with new LoRA adapters")
            peft_config = LoraConfig(
                target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
                r=r,
                lora_alpha=lora_alpha,
                lora_dropout=0.05,
                task_type="CAUSAL_LM",
                inference_mode=False,
            )
            model = get_peft_model(model, peft_config)
    else:
        print("Initializing inference-time model from pre-trained weights")
    return model, tokenizer
