import argparse

from dialogue_kt.annotate import annotate
from dialogue_kt.human_eval import human_eval
from dialogue_kt.training import train, test, BASELINE_MODELS
from dialogue_kt.visualize import visualize
from dialogue_kt.utils import initialize_seeds, bool_type

def main():
    initialize_seeds(221)

    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers()

    parser_annotate = subparsers.add_parser("annotate", help="Annotate dialogues")
    parser_annotate.set_defaults(func=annotate)
    parser_annotate.add_argument("--mode", type=str, choices=["collect", "analyze"], help="Collect annotations or analyze existing files")
    parser_annotate.add_argument("--use_azure", action="store_true", help="Use Azure endpoint")
    parser_annotate.add_argument("--openai_model", type=str, help="Model identifier string")

    parser_hum_eval = subparsers.add_parser("human-eval", help="Create/analyze human evaluation files")
    parser_hum_eval.set_defaults(func=human_eval)
    parser_hum_eval.add_argument("--mode", type=str, choices=["create", "analyze"], help="Create evaluation files or analyze existing files")

    parser_train = subparsers.add_parser("train", help="Train KT model")
    parser_train.set_defaults(func=train)
    parser_train.add_argument("--epochs", type=int, help="Number of training epochs")
    parser_train.add_argument("--lr", type=float, help="Learning rate")
    parser_train.add_argument("--wd", type=float, help="Weight decay")
    parser_train.add_argument("--gc", type=float, help="Gradient clipping norm")
    parser_train.add_argument("--grad_accum_steps", type=int, help="Steps to accumulate gradients for")
    parser_train.add_argument("--r", type=int, help="LoRA rank")
    parser_train.add_argument("--lora_alpha", type=int, help="LoRA alpha")
    parser_train.add_argument("--optim", type=str, choices=["adamw", "adafactor"], default="adamw", help="Optimizer")
    parser_train.add_argument("--pt_model_name", type=str, help="Name of pre-trained model to initialize weights from")
    parser_train.add_argument("--hyperparam_sweep", action="store_true", help="Run a hyperparameter sweep experiment")

    parser_test = subparsers.add_parser("test", help="Test KT model")
    parser_test.set_defaults(func=test)

    parser_visualize = subparsers.add_parser("visualize", help="Visualize KCs")
    parser_visualize.set_defaults(func=visualize)

    for subparser in [parser_annotate, parser_hum_eval, parser_train, parser_test, parser_visualize]:
        subparser.add_argument("--dataset", type=str, choices=["comta", "mathdial"], default="comta", help="Which dataset to use")
        subparser.add_argument("--split_by_subject", action="store_true", help="For CoMTA, define train/test and folds using subjects")
        subparser.add_argument("--typical_cutoff", type=int, default=1, help="For MathDial, lowest acceptable dialogue 'typical' score")
        subparser.add_argument("--tag_src", type=str, choices=["base", "atc"], default="atc", help="Source of KC tags - base: generated by LLM, atc: ATC standards")
        subparser.add_argument("--debug", action="store_true", help="Use subset of data for debugging")

    for subparser in [parser_train, parser_test, parser_visualize]:
        subparser.add_argument("--model_type", type=str, choices=["lmkt", "random", "majority", "bkt"] + BASELINE_MODELS, default="lmkt", help="Model architecture to use")
        subparser.add_argument("--model_name", type=str, help="Name of model to save for training or load for testing")
        subparser.add_argument("--base_model", type=str, default="Qwen/Qwen3-1.7B", help="HuggingFace base model for LLMKT")
        subparser.add_argument("--inc_first_label", action="store_true", help="Include first turn label in dialogues when testing")

    for subparser in [parser_train, parser_test]:
        subparser.add_argument("--batch_size", type=int, help="Model batch size")
        subparser.add_argument("--crossval", action="store_true", help="Run training/testing over all folds and aggregate results")
        subparser.add_argument("--testonval", action="store_true", help="Run testing phase on validation set (automatic for hyperparam_sweep)")
        subparser.add_argument("--agg", type=str, choices=["prod", "mean-ar", "mean-geo"], default="mean-ar", help="Method for aggregating KC probabilities into correctness probability")
        subparser.add_argument("--pack_kcs", type=bool_type, default=True, help="For LLMKT, pack all KCs for a turn in a single prompt")
        subparser.add_argument("--quantize", type=bool_type, default=True, help="Quantize LLMKT base model")
        subparser.add_argument("--prompt_inc_labels", type=bool_type, default=False, help="For LLMKT, include explicit correctness and KC labels in prompt")
        subparser.add_argument("--emb_size", type=int, help="Latent state dimension for DKT family models")
        subparser.add_argument("--selfelicit", type=str, choices=["prompt", "inference", "weighted", "combined"], default=None,
                               help="SELFELICIT mode: prompt=evidence-marked prompts, inference=two-pass test, weighted=attention-weighted aggregation, combined=prompt+weighted")
        subparser.add_argument("--bayes_evidence", type=str, choices=["adaptive", "recent2", "recent3", "adaptive_labels"], default=None,
                               help="Bayesian epistemology prompt mode: evidence reliability markers, optionally with past labels")
        subparser.add_argument("--informativeness", type=str, choices=["novelty", "novelty_recent", "recent_grounded", "novelty_prune", "novelty_recent_prune", "recent_prune"], default=None,
                               help="Stepwise informativeness prompt mode: mark/prune underutilized non-redundant dialogue steps")
        subparser.add_argument("--kt_method", type=str,
                               choices=["base", "state_table", "solution_contrast", "support_token", "hyper_chain", "quito_mark", "dac_mark", "mil_noisy_and", "rank_auc", "dual_view_consistency", "evidence_r1", "hyper_validate", "ib_turns"],
                               default="base", help="Standalone trainable Dialogue-KT method variant")
        subparser.add_argument("--kt_prompt_method", type=str,
                               choices=["base", "state_table", "solution_contrast", "support_token", "hyper_chain", "quito_mark", "dac_mark", "evidence_r1", "hyper_validate", "ib_turns"],
                               default=None, help="Override prompt method (defaults to kt_method)")
        subparser.add_argument("--kt_loss_method", type=str,
                               choices=["base", "mil_noisy_and", "rank_auc", "dual_view_consistency"],
                               default=None, help="Override loss method (defaults to kt_method)"))
        subparser.add_argument("--aux_loss_weight", type=float, default=0.2, help="Auxiliary loss weight for KT method variants")
        subparser.add_argument("--rank_loss_weight", type=float, default=0.1, help="Pairwise ranking loss weight")
        subparser.add_argument("--rank_margin", type=float, default=0.05, help="Pairwise ranking margin")
        subparser.add_argument("--state_top_k", type=int, default=8, help="Maximum rows in state-table prompts")
        subparser.add_argument("--consistency_weight", type=float, default=0.15, help="Dual-view consistency loss weight")
        subparser.add_argument("--dual_view_type", type=str, choices=["state_table", "solution_contrast"], default="state_table", help="Second view for dual-view consistency")

    args = parser.parse_args()
    args.func(args)

if __name__ == "__main__":
    main()
